create database Project
use Project

create Table Academic_Officer(
AD_ID VARCHAR(20) NOT NULL,
AD_USERNAME VARCHAR(50) NOT NULL,
AD_PASSWORD VARCHAR(50) NOT NULL,
AD_AGE INT NOT NULL,
AD_EMAIL VARCHAR(50)NOT NULL,
AD_PHONE VARCHAR(50)NOT NULL,
AD_ROLE CHAR(1)NOT NULL CHECK (AD_ROLE='A'),
PRIMARY KEY(AD_ID)
);


create table STUDENTS
( ST_ID VARCHAR(20) NOT NULL,
ST_USERNAME VARCHAR(50)NOT NULL,
ST_PASSWORD VARCHAR(50)NOT NULL,
ST_AGE INT NOT NULL,
ST_EMAIL VARCHAR(50) NOT NULL,
ST_PHONE VARCHAR(50) NOT NULL,
ST_DEPT VARCHAR(50) NOT NULL,
ST_ROLE CHAR(1) NOT NULL CHECK (ST_ROLE='S'),
ST_SECTION VARCHAR(10) NOT NULL,
ST_YEAR VARCHAR(10) NOT NULL,
PRIMARY KEY(ST_ID)
);

create table FACULTY

( FT_ID VARCHAR(20) NOT NULL,
FT_USERNAME VARCHAR(50) NOT NULL,
FT_PASSWORD VARCHAR(50) NOT NULL,
FT_AGE INT NOT NULL,
FT_EMAIL VARCHAR(50) NOT NULL,
FT_PHONE VARCHAR(50) NOT NULL,
FT_ROLE CHAR(1) NOT NULL CHECK (FT_ROLE='F'),
FT_DEPT VARCHAR(50) NOT NULL,
FT_TYPE VARCHAR(20) CHECK (FT_TYPE='INS' OR FT_TYPE='LAB-INS'),
PRIMARY KEY(FT_ID)
);

create table COURSE
( COURSE_CODE varchar(20) NOT NULL,
COURSE_NAME	 varchar(60) NOT NULL,
CREDIT_HOURS int NOT NULL,
POST_REQ varchar(50)NOT NULL,
SEMESTER varchar(50) NOT NULL,
DEPT varchar(50) NOT NULL,
COURSE_COORDINATOR_ID	varchar(20)	NOT NULL
PRIMARY KEY(COURSE_CODE)
FOREIGN KEY (COURSE_COORDINATOR_ID) REFERENCES FACULTY(FT_ID)
);


create table ST_COURSE_REG
( 
STU_ID VARCHAR(20) NOT NULL,
COURSE_ID VARCHAR(20) NOT NULL,
PRIMARY KEY(STU_ID,COURSE_ID),
FOREIGN KEY (STU_ID) REFERENCES STUDENTS(ST_ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_CODE)
);

CREATE TABLE TEACHES(
T_ID INT NOT NULL,
FCT_ID VARCHAR(20) NOT NULL,
COURSE_ID VARCHAR(20) NOT NULL,
SECTION VARCHAR(10) NOT NULL,
YEAR VARCHAR(10) NOT NULL,
PRIMARY KEY(T_ID),
FOREIGN KEY (FCT_ID) REFERENCES FACULTY(FT_ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_CODE)
);



CREATE TABLE STUDENT_ATTENDANCE
(
ST_ID VARCHAR(20) NOT NULL,
T_ID INT NOT NULL,
SECTION VARCHAR(10) NOT NULL,
ATTENDANCE VARCHAR(10) NOT NULL,
ATT_DATE DATE NOT NULL
);

create table MARKS_DIST
( T_ID varchar(20) ,
  ASSIGN INT,
  FINAL INT,
  QUIZ INT,
  SESSIONALI INT,
  SESSIONALII INT
);

Create table log(
Activity varchar(200), 
Date_Activity date);

CREATE TABLE STUDENTS_MARKS
(
ST_ID VARCHAR(20) NOT NULL,
T_ID INT NOT NULL,
SECTION VARCHAR(10) NOT NULL,
ASSIGNMENT INT NOT NULL,
FINAL_EXAM INT NOT NULL,
QUIZ INT NOT NULL,
SESSIONAL_I INT NOT NULL,
SESSIONAL_II INT NOT NULL,
);

Create table feedback(
Q_NO INT,
Response INT  not null check(Response>=1 and Response<=5));

select* from Academic_Officer
select* from ST_COURSE_REG
SELECT * FROM COURSE
select* from Faculty
select* from MARKS_DIST
select* from TEACHES
SELECT * FROM STUDENT_ATTENDANCE
select* from STUDENTS_MARKS
select* from STUDENTS

--------------------------------LOADING DATA FROM EXCEL SHEET-------------------------------

insert into Academic_Officer(AD_ID,AD_USERNAME,AD_PASSWORD,AD_AGE,AD_EMAIL,AD_PHONE,AD_ROLE)
select* from Academic_Officer$

insert into FACULTY(FT_ID,FT_USERNAME,FT_PASSWORD,FT_AGE,FT_EMAIL,FT_PHONE,FT_ROLE,FT_DEPT,FT_TYPE)
select* from FACULTY$

insert into STUDENTS(ST_ID,ST_USERNAME,ST_PASSWORD,ST_AGE,ST_EMAIL,ST_PHONE,ST_DEPT,ST_ROLE,ST_SECTION,ST_YEAR)
select* from STUDENT$

insert into COURSE(COURSE_CODE,COURSE_NAME,CREDIT_HOURS,POST_REQ,SEMESTER,DEPT,COURSE_COORDINATOR_ID)
select* from COURSE$


INSERT INTO ST_COURSE_REG(STU_ID,COURSE_ID)
select* from ST_COURSE_REG$ 

INSERT INTO TEACHES(T_ID,FCT_ID,COURSE_ID,SECTION,YEAR)
select* from TEACHES$ 

insert into STUDENT_ATTENDANCE(ST_ID,T_ID,SECTION,ATTENDANCE,ATT_DATE)
select* from  STUDENT_ATTENDANCE$

----------------------------------------------------------------------------------------------------------------------------------------
